apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  labels:
    app: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: wordpress
  type: LoadBalancer
  loadBalancerIP: 192.168.99.2
  ports:
    - protocol: TCP
      name: http
      port: 5050
      targetPort: 5050
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress_image
          imagePullPolicy: Never
          ports:
            - containerPort: 5050
